name: AutomaticTesting
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master
      -run: cd ./server/express_server
      -run: npm install
      -run: npm run test